### ISSUE TITLE
Utilidad del repo

### ISSUE THREAD

**Issue by ramaroberto** [CubaWiki/LyC#1]
Buenas! Note que aparentemente la utilidad de este repo es solamente redirigir a otro repo dentro de la misma organizacion. Esta hecho a proposito o simplemente se traspapelo?

Dejo el issue para que llegue la notificacion solamente.

Abrazo!

**Comment by ramaroberto** [comment]
Ups, me acabo de dar cuenta que es una especie de indice "Apuntes de LyC". Disculpas!

Quizas estaria bueno flaggear a los repos que son indices de alguna forma, por ejemplo con algun prefijo.

Cierro.

**Comment by FlyingPumba** [comment]
jaja no hay problema ! En su momento se hizo a propósito como un índice (parecido al de [ISW2](https://github.com/CubaWiki/ISW2) y otros).
Si algún día nos decidimos porque no sirven los podemos borrar, la verdad que eso mismo podría estar (y en muchos está) en CubaWiki.
